name: Build and create release

on:
  workflow_dispatch:
jobs:
  Build-And-Release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - self-hosted
    runs-on: ${{matrix.os}}
    name: Build and release ${{matrix.os}}
    steps:

      - name: Set build name
        shell: bash
        run: |
          {
            if [ "${{matrix.os}}" = "ubuntu-latest" ]; then
              echo build_name=linux-amd64

            elif [ "${{matrix.os}}" = "macos-latest" ]; then
              echo build_name=darwin-amd64

            elif [ "${{matrix.os}}" = "windows-latest" ]; then
              # do not remove the file extension,
              # softprops/action-gh-release action will fail
              # "Pattern 'r-type_*-windows-amd64' does not match any files."
              echo build_name=windows-amd64.exe

            elif [ "${{matrix.os}}" = "self-hosted" ]; then
              # change this, repo's self-hosted runner is Debian arm64
              echo build_name=linux-arm64

            else
              exit 1
            fi
          } >> $GITHUB_ENV
          exit 0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set release name
        shell: bash
        run: echo release_name=release-$(git rev-parse --short $GITHUB_SHA) >> $GITHUB_ENV

      - name: Build
        run: bash install.sh

      - name: Check build
        shell: bash
        run: |
          ls -1
          test -f r-type_client
          test -f r-type_server

      - name: Rename build
        shell: bash
        run: |
          mv r-type_client r-type_client-${{env.build_name}}
          mv r-type_server r-type_server-${{env.build_name}}

      - name: Archive build
        shell: bash
        run: |
          7z a r-type-${{env.build_name}}.7z r-type_{client,server}-${{env.build_name}}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.release_name}}
          files: r-type-${{env.build_name}}.7z
          fail_on_unmatched_files: true
