name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - self-hosted
    runs-on: ${{matrix.os}}
    name: Build ${{matrix.os}}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build
        run: bash install.sh

      - name: DEBUG
        shell: bash
        run: |
          ls -l || true
          ls -l Debug || true

      - name: Check build (Windows)
        if: matrix.os == 'windows-latest'
        uses: andstor/file-existence-action@v1
        with:
          files: "Debug/r_type-client, Debug/r_type-server"

      - name: Check build
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          test -f r-type_client
          test -f r-type_server
