name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SFML
        run: |
          sudo apt install libsfml-dev
          apt list --installed | grep -i sfml
      - name: build on Ubuntu
        run: |
          mkdir build
          cd build && cmake ..
          cmake --build .
      - name: check build
        run: test -f r-type

  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: build on Windows
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build .
      - name: check build
        run: Test-Path r-type
