name: Build and create release

on:
  workflow_dispatch:
env:
  RUNNER: true

jobs:
  Build-And-Release:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
    runs-on: ${{matrix.os}}
    name: Build and release ${{matrix.os}}
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build
        run: bash install.sh --installer

      - name: Check build
        shell: bash
        run: find . -type f > files.txt

      - uses: actions/upload-artifact@v3
        with:
          name: files
          path: files.txt

     # - name: Rename build (Windows)
     #   if: matrix.os == 'windows-latest'
     #   shell: bash
     #   run: |
     #     mv Debug/r-type_client.exe r-type_client-${{env.build_name}}
     #     mv Debug/r-type_server.exe r-type_server-${{env.build_name}}

     # - name: Rename build
     #   if: matrix.os != 'windows-latest'
     #   shell: bash
     #   run: |
     #     mv r-type_client r-type_client-${{env.build_name}}
     #     mv r-type_server r-type_server-${{env.build_name}}

     # - name: Archive build
     #   shell: bash
     #   run: 7z a ${{env.archive_name}} r-type_{client,server}-${{env.build_name}}

     # - name: Create release
     #   uses: softprops/action-gh-release@v1
     #   with:
     #     tag_name: ${{env.release_name}}
     #     files: ${{env.archive_name}}
     #     fail_on_unmatched_files: true
