name: Actions

on:
  workflow_dispatch:

jobs:
  Build-And-Release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          - self-hosted

    runs-on: ${{matrix.os}}
    name: Build on ${{matrix.os}}
    steps:

      - name: Set build name
        shell: bash
        run: |
          {
            if [ "${{matrix.os}}" = "ubuntu-latest" ]; then
              echo build_name=linux-amd64

            elif [ "${{matrix.os}}" = "macos-latest" ]; then
              echo build_name=darwin-amd64

            elif [ "${{matrix.os}}" = "windows-latest" ]; then
              # do not remove the file extension,
              # softprops/action-gh-release action will fail
              # "Pattern 'R-Type-*-windows-amd64' does not match any files."
              echo build_name=windows-amd64.exe

            elif [ "${{matrix.os}}" = "self-hosted" ]; then
              # change this, repo's self-hosted runner is Debian arm64
              echo build_name=linux-arm64

            else
              exit 1
            fi
          } >> $GITHUB_ENV
          exit 0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set release name
        shell: bash
        run: echo release_name=release-$(git rev-parse --short $GITHUB_SHA) >> $GITHUB_ENV

      - name: Build
        run: bash install.sh

      - name: Check builds
        shell: bash
        run: |
          test -f R-Type-client-${{env.build_name}}
          test -f R-Type-server-${{env.build_name}}

      - name: Rename builds
        shell: bash
        run: |
          mv R-Type-client R-Type-client-${{env.build_name}}
          mv R-Type-server R-Type-server-${{env.build_name}}

      - name: Archive builds
        shell: bash
        run: |
          7z a R-Type-${{env.build_name}}.7z R-Type-{client,server}-${{env.build_name}}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.release_name}}
          files: R-Type-${{env.build_name}}.7z
          fail_on_unmatched_files: true
